#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # Get the script's current directory


function printUsage {
echo -e "Usage:\n\t-l:\tFilename to take links from\n\t-q:\tEnables quiet mode";
}

enableQuiet=false

while getopts "l:q" o; do
    case "${o}" in
        l)
            linksFile=${OPTARG}
            ;;
        q)
            enableQuiet=${OPTARG}
            ;;
        *)
	    printUsage
	    exit -1
            ;;
    esac
done
shift $((OPTIND-1))

if [[ "$linksFile" == "" ]]; then
	linksFile="links"
	if [[ $enableQuiet == false ]]; then
		echo -e "\n\nAssuming links file is \"links\""
	fi
fi



mkdir $DIR/downloads
cd $DIR/downloads


function parse {
grep -o -E 'href="([^"#]+)"' $1 | cut -d'"' -f2 | sort | uniq | grep -E '.jpg|.png' >> temp
grep -o -E 'href="([^"#]+)"' $2 | cut -d'"' -f2 | sort | uniq | grep -E '.jpg|.png' >> temp
grep -o -E 'href="([^"#]+)"' $3 | cut -d'"' -f2 | sort | uniq | grep -E '.jpg|.png' >> temp
grep -o -E 'href="([^"#]+)"' $4 | cut -d'"' -f2 | sort | uniq | grep -E '.jpg|.png' >> temp
}

function downloadPages {
rname=$( echo $1 | cut -d / -f 5  )
tname=$(echo t.$rname)
rrname=$(echo r.$rname)
cname=$(echo c.$rname)
wget --load-cookies=../cookies.txt -O $rname $1  &>/dev/null &
wget --load-cookies=../cookies.txt -O $tname $1/top &>/dev/null &
wget --load-cookies=../cookies.txt -O $rrname $1/rising &>/dev/null &
wget --load-cookies=../cookies.txt -O $cname $1/controversial &>/dev/null &
wait
parse $rname $tname $rrname $cname
}


if [[ $enableQuiet == false ]]; then
	cat $DIR/$linksFile | cut -d\/ -f "5" | column -x
fi


# Sometimes reddit doesn't populate the pages quick enough! We need to check there are images to download, if not try again
while [ -z $wallpaper ]; do

	subRedditChosenFrom="$(shuf -n 1 ../$linksFile)"
	downloadPages "$subRedditChosenFrom"&
	pids+=" "$!""

	wait # wait for all processes to return

	# remove reddit pics that exist on most pages from the list
	sed -i '/www.redditstatic.com\//d' temp
	sed -i '/styles.redditmedia.com\//d' temp
	sed -i '/i.imgur.com\/ZDka3tA.png/d' temp
	sed -i '/i.imgur.com\/vFrZ1C9.png/d' temp
	sed -i '/i.imgur.com\/FqnC5e2.png/d' temp
	sed -i '/i.imgur.com\/4PxSX4e.png/d' temp

	# select randomly from file and DL
	wallpaper=$(shuf -n 1 temp)

	if [[ $enableQuiet == false && ! -z $wallpaper ]]; then
       		rname=$( echo $subRedditChosenFrom | cut -d / -f 5  )
		echo -e "\nGrabbing image from r/$rname!"
	fi

done

echo -e "From r/$(echo $subRedditChosenFrom | cut -d '/' -f 5)" >> ../log
echo $wallpaper >> ../log
echo -e "\n" >> ../log

wget -b $wallpaper -O $DIR/wallpaperpic 1>/dev/null&
wait
gsettings set org.gnome.desktop.background picture-uri file://$DIR/wallpaperpic
#gsettings set org.gnome.desktop.background picture-options "zoom"

# cleanup
cd ~
rm -r $DIR/downloads
